# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

pool:
  vmImage: 'vs2017-win2016'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.10'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    testResultsFiles: '**/TEST-*.xml'
    goals: 'package'

# TESTING GitHub Release
# Create, edit, or discard a GitHub release.
- task: GithubRelease@0
  inputs:
    gitHubConnection: marlenelund
    repositoryName: Statoil/neqsimsource
    action: create # Options: create, edit, discard
    target: $(build.sourceVersion) # Required when action == create || action == edit
    tagSource: auto # Required when action == create. Options: auto, manual
    tag: $(tagName) # Required when action == edit || action == discard || tagSource == manual
    #title: # Optional
    #releaseNotesSource: 'file' # Optional. Options: file, input
    #releaseNotesFile: # Optional
    #releaseNotes: # Optional
    #assets: '$(build.artifactStagingDirectory)/*' # Optional
    #assetUploadMode: 'delete' # Optional. Options: delete, replace
    #isDraft: false # Optional
    isPreRelease: false # Optional
    #addChangeLog: true # Optional
