name: Build maven J8 and J11

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: savelibJ11
        run: mkdir staging && cp target/*.jar staging
        uses: actions/upload-artifact@v2
        with:
          name: jarfiles
          path: staging
